python scripts/sample_near_embeddings.py \
    --input_embeddings data/mae_embeddings/embeddings.npy \
    --index 29 \
    --num_samples 25 \
    --near_mode sparse_noise \
    --subset_frac 0.2 \
    --noise_mag 0.2 \
    --preserve_norm \
    --output_path outputs/embed_diffusion/near_samples_29.npy \
    --real_embeddings data/mae_embeddings/embeddings.npy \
    --match_stats \
    --seed 42 \
    --dataroot ../../PSF/data/ShapeNetCore.v2.PC15k/ \
    --category chair \
    --npoints 2048 \
    --ref_output_path outputs/embed_diffusion/near_ref_29.png
