python scripts/infer_mae_interpolate.py \
    --checkpoint checkpoints/jmae500/best.pth \
    --dataroot ../../PSF/data/ShapeNetCore.v2.PC15k/ \
    --category chair \
    --voxel_size 32 \
    --npoints 2048 \
    --mae_config_path configs/pretrainMAE.yaml \
    --mae_points 1024 \
    --mae_mask_ratio 0.6 \
    --steps 5 \
    --device cuda:0 \
    --output_dir outputs/mae_interpol42 \
    --seed 42 \
    --use_ema \
    --interp_mode slerp
